protected/models/Teachers.php
<?php

/**
 * This is the model class for table "teachers".
 *
 * The followings are the available columns in table 'teachers':
 * @property integer $id
 * @property integer $userId
 * @property string $daraja
 * @property integer $staj
 * @property string $soli_kabul
 * @property string $datecreate
 * @property string $lastupdate
 * @property integer $status
 *
 * The followings are the available model relations:
 * @property Subject[] $subjects
 * @property User $user
 */
class Teachers extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Teachers the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'teachers';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('userId, daraja, staj, soli_kabul, datecreate, lastupdate, status', 'required'),
			array('userId, staj, status', 'numerical', 'integerOnly'=>true),
			array('daraja', 'length', 'max'=>6),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, userId, daraja, staj, soli_kabul, datecreate, lastupdate, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'subjects' => array(self::HAS_MANY, 'Subject', 'teacherId'),
			'user' => array(self::BELONGS_TO, 'User', 'userId'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'userId' => 'User',
			'daraja' => 'Daraja',
			'staj' => 'Staj',
			'soli_kabul' => 'Soli Kabul',
			'datecreate' => 'Datecreate',
			'lastupdate' => 'Lastupdate',
			'status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('userId',$this->userId);
		$criteria->compare('daraja',$this->daraja,true);
		$criteria->compare('staj',$this->staj);
		$criteria->compare('soli_kabul',$this->soli_kabul,true);
		$criteria->compare('datecreate',$this->datecreate,true);
		$criteria->compare('lastupdate',$this->lastupdate,true);
		$criteria->compare('status',$this->status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/TeacherController.php
<?php

class TeacherController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
           array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('study','darsho','karz','ball','setball','setbal2','dellball','goib','teach'),
                'roles'=>array('2'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionStudy()
    {

      $this->render('study');
    }

    public function actionGoib($id)
    {

        $shedual = $this->loadShedual($id);
        $this->render('goib/absents', array('shedual' => $shedual));
    }

    public function actionDarsho()
    {


        $this->render('goib/ruihat');
    }

    public function actionBall($id)
    {
        $decode = intval($id);
        $shedual = $this->loadShedual(Users::getDecode($decode));
        $subject = $this->loadSubject($shedual->subjectId);

        $this->render('ball', array('shedual' => $shedual, 'subject' => $subject));
    }

    public function actionSetball()
    {


        if (isset($_POST['shedId']) || isset($_POST['userId']) || isset($_POST['type']) || isset($_POST['ball'])) {


            $shedualId = ($_POST['shedId']);
            $userId = ($_POST['userId']);
            $type = ($_POST['type']);
            $ball = intval($_POST['ball']);

            $group = Groupin::model()->findByPk($userId);
            $user = Users::getUser($group->userId);
            $count = Scores::model()->findByAttributes(
                array(
                    'shedualId' => $shedualId,
                    'groupinId' => $userId,
                    'typeId' => $type,

                ));

            if (count($count) == 0) {
                $newScores = new Scores();
                $newScores->shedualId = $shedualId;
                $newScores->groupinId = $userId;
                $newScores->typeId = $type;

                if ($ball > 10) {
                    $newball = $newScores->bal = 10;
                } elseif ($ball < 0) {
                    $newball = $newScores->bal = 0;
                } else {
                    $newball = $newScores->bal = $ball;
                }

                $newScores->datecreate = new CDbExpression('NOW()');
                $newScores->lastupdate = new CDbExpression('NOW()');
                $newScores->status = 1;
                if ($newScores->save()) {

                    echo '<img src=' . Yii::app()->request->baseUrl . $user->avatar . ' alt="avatar" width="40" style="margin-right:10px;border-radius: 25px;">';

                    echo $user->fname . ' ' . mb_substr($user->name,0,1,"UTF-8") . ', Балл:  ' . $newball;
                } else {
                    echo 'Error not insert';
                }

            } elseif (count($count) == 1) {

                $upd = Scores::model()->updateByPk($count->idScores,
                    array(
                        'shedualId' => $shedualId,
                        'groupinId' => $userId,
                        'bal' => $ball,
                        'typeId' => $type,
                        'lastupdate' => new CDbExpression('NOW()')
                    )
                );
                echo '<img src=' . Yii::app()->request->baseUrl . $user->avatar . ' alt="avatar" width="40" style="margin-right:10px;border-radius: 25px;">';
                echo $user->fname . ' ' . mb_substr($user->name,0,1,"UTF-8") . ',&nbsp;&nbsp;Азнавшуд:  ' . $_POST['ball'];


            }
        }
    }

    public function actionDellball(){
        if (isset($_POST['sId']) || isset($_POST['uId']) || isset($_POST['t']) && Yii::app()->request->isAjaxRequest) {
            $shedId = ($_POST['sId']);
            $userId = ($_POST['uId']);
            $t = ($_POST['t']);

            $count = Scores::model()->findByAttributes(
                array(
                    'shedualId' => $shedId,
                    'groupinId' => $userId,
                    'typeId' => $t,

                ));
            if (count($count) == 0) {
                echo 0;
            } else {
                $this->loadScores($count->idScores)->delete();
                echo 1;
            }
        }
    }
    public function actionTeach()
    {


        $uId = intval($_POST['userId']);
        $sId = intval($_POST['shedualId']);
        $type = intval($_POST['type']);
        $sum=0;
        if (isset($_POST['check1'])) {
            Users::insertCheckAbsents($uId, $sId, $type, 1,"Tabsent");
            $sum=$sum+1;
        }
        if (isset($_POST['check2'])) {
            Users::insertCheckAbsents($uId, $sId, $type, 2,"Tabsent");
            $sum=$sum+1;
        }
        if (isset($_POST['check3'])) {
            Users::insertCheckAbsents($uId, $sId, $type, 3,"Tabsent");
            $sum=$sum+1;
        }


        //}


        echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="label label-danger">'.$sum.'</span>
                </a>';
    }

    public static function actionSetbal2()
    {
        if (isset($_POST['tId']) || isset($_POST['sid'])) {
            $sid = (int)$_POST['sid'];
            $tid = (int)$_POST['tId'];
            $check = Checktable::model()->find(array('condition' => 'shedualId=' . $sid . ' and typeId=' . $tid));
            if (count($check) == 0) {
                if($tid==8){
                $insert=Users::InsertCheck($sid, $tid);
                    Users::InsertCheck($sid, 9);
                }elseif($tid==17){
                    $insert=Users::InsertCheck($sid, $tid);
                    Users::InsertCheck($sid, 18);
                }else{
                    $insert=Users::InsertCheck($sid, $tid);
                }
                    if ($insert == 1) {
                    echo 1;
                } else echo 0;
            } else echo 2;
        }
    }

        /* LOAD MODELS  */

    public function loadShedual($id)
    {
        $model = Shedual::model()->findByPk($id, array('condition' => 'status=1'));
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    public function loadSubject($id)
    {
        $model = Subject::model()->findByPk($id, array('condition' => 'status=1'));
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    public function loadScores($id)
    {
        $model = Scores::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }
} 

protected/views/teacher/goib/_absent.php
<?php
$a=1;
foreach ($groupClass as $class){

        echo '<tr>';
        echo '<td>'.$a++.'</td>';
    if($class->user->lname=="."){
        echo '<td>'.$class->user->fname.' '.$class->user->name.'</td>';
    }else
        echo '<td>'.$class->user->fname.' '.$class->user->name.' '.$class->user->lname.'</td>';
      //  echo '<td>'.$shedual->idShedual.'</td>';
      //  echo '<td>'.$class->idGroupin.'</td>';
        foreach($ruzho as $ruz){
            
        $scores=  Users::getTabsent($shedual->idShedual,$class->idGroupin,$ruz->id);
        $sum_score = Users::getSumTabsent($shedual->idShedual,$class->idGroupin,$ruz->id);
        $absents = Users::getTAbsents($shedual->idShedual,$class->idGroupin,$ruz->id);
        if($ruz->id==9){
                if(count($scores)!=NULL){
                                    ?>
<td style="vertical-align: inherit;font-size: 18px;" bgcolor="#C7C7C7" id="getUpd_<?php echo $ruz->id . $class->idGroupin ; ?>" align="center">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="label label-danger"><?php echo "ғ";?></span>
                </a>
                
</td>
                
                <?php
                
                }else{
                        echo '<td id="getUpd_' . $ruz->id . $class->idGroupin . '" style="vertical-align: inherit;" bgcolor="#C7C7C7" align="center" class="dropdown messages-menu">';
                        echo '<form id="theForm_'.$ruz->id.$class->idGroupin.'">';
                        echo CHtml::hiddenField('type', $ruz->id, array('id'=>'type'));
                        echo CHtml::hiddenField('shedualId', $shedual->idShedual,array('id'=>'shedId'));
                        echo CHtml::hiddenField('userId', $class->idGroupin,array('id'=>'userId'));
                        ?>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            </a>
                            <ul class="dropdown-menu">
                            <li class="footer">

                                    <div class="btn-group">
                                    <span  style="padding: 3px 6px" class="btn btn-danger"><input type="checkbox" name="check1" class="check" id="check_<?php echo $ruz->id.$class->idGroupin; ?>" value="1">1</span>
                                    </div>
                                <button class="btn btn-success" onfocus="sendAbsent(<?php echo $ruz->id.$class->idGroupin; ?>)" id="abs_<?php echo $ruz->id.$class->idGroupin; ?>" type="button">OK</button>


                            </li>
                        </ul>
                <?php
                echo '</form>';
                        echo '</td>';
                        }
        
        }elseif($ruz->id==18){
            if(count($scores)!=NULL){
                                    ?>
<td style="vertical-align: inherit;font-size: 18px;" bgcolor="#C7C7C7" id="getUpd_<?php echo $ruz->id . $class->idGroupin ; ?>" align="center">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="label label-danger"><?php echo'ғ';?></span>
                </a>
             
</td>
                
                <?php
                }else{
            echo '<td id="getUpd_' . $ruz->id . $class->idGroupin . '" style="vertical-align: inherit;" bgcolor="#C7C7C7" align="center" class="dropdown messages-menu">';
            echo '<form id="theForm_'.$ruz->id.$class->idGroupin.'">';
            echo CHtml::hiddenField('type', $ruz->id, array('id'=>'type'));
            echo CHtml::hiddenField('shedualId', $shedual->idShedual,array('id'=>'shedId'));
            echo CHtml::hiddenField('userId', $class->idGroupin,array('id'=>'userId'));
            ?>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </a>
                <ul class="dropdown-menu">
                 <li class="footer">
                      
                        <div class="btn-group">
                          <span  style="padding: 3px 6px" class="btn btn-danger"><input type="checkbox" name="check1" class="check" id="check_<?php echo $ruz->id.$class->idGroupin; ?>" value="1">1</span>
                        </div>
                      <button class="btn btn-success" onfocus="sendAbsent(<?php echo $ruz->id.$class->idGroupin; ?>)" id="abs_<?php echo $ruz->id.$class->idGroupin; ?>" type="button">OK</button>
                     

                  </li>
              </ul>
                <?php
            echo '</form>';
            echo '</td>';
             }
        }else{
            if(count($scores)!=NULL){
                                    ?>
<td style="vertical-align: inherit;font-size: 18px;" bgcolor="#C7C7C7" align="center" id="getUpd_<?php echo $ruz->id . $class->idGroupin ; ?>" class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="label label-danger"><?php echo $sum_score;?></span>
                </a>
                <ul class="dropdown-menu">
                  <li class="footer">
                          <div class="btn-group">
                          <?php
                          
                         foreach ($absents as $absent){
                             if($absent->checkId==1){
                                echo '<button type="button" style="padding: 3px 6px" class="btn btn-danger"><i class="fa fa-clock-o">1</i></button>';
                             }elseif($absent->checkId==2){
                             echo '<button type="button" style="padding: 3px 6px" class="btn btn-danger"><i class="fa fa-clock-o">2</i></button>';
                             }elseif($absent->checkId==3){
                             echo '<button type="button" style="padding: 3px 6px" class="btn btn-danger"><i class="fa fa-clock-o">3</i></button>';
                             }
                             
                         }
                          ?>
                        </div>
                  </li>
                </ul>
</td>
                
                <?php
                }else{
                echo '<td id="getUpd_' . $ruz->id . $class->idGroupin . '" style="vertical-align: inherit;"  align="center" id="rel_'.$ruz->id.$class->idGroupin.'"  class="dropdown messages-menu">';
                echo '<form id="theForm_' . $ruz->id . $class->idGroupin . '">';
                echo CHtml::hiddenField('type', $ruz->id, array('id' => 'type'));
                echo CHtml::hiddenField('shedualId', $shedual->idShedual, array('id' => 'shedId'));
                echo CHtml::hiddenField('userId', $class->idGroupin, array('id' => 'userId'));
                ?>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </a>
                <ul class="dropdown-menu">
                 <li class="footer">
                      
                        <div class="btn-group">
                          <span  style="padding: 3px 6px" class="btn btn-danger"><input type="checkbox" name="check1" class="check" id="check_<?php echo $ruz->id.$class->idGroupin; ?>" value="1">1</span>
                          <span  style="padding: 3px 6px" class="btn btn-danger"><input type="checkbox" name="check2" class="check" id="check_<?php echo $ruz->id.$class->idGroupin; ?>" value="2">2</span>
                          <span  style="padding: 3px 6px" class="btn btn-danger"><input type="checkbox" name="check3" class="check" id="check_<?php echo $ruz->id.$class->idGroupin; ?>" value="3">3</span>
                        </div>
                      <button class="btn btn-success" onfocus="sendAbsent(<?php echo $ruz->id.$class->idGroupin; ?>)" id="abs_<?php echo $ruz->id.$class->idGroupin; ?>" type="button">OK</button>
                     

                  </li>
              </ul>
                <?php
                echo '</form>';
                echo '</td>';
                }
        }
        }
        
        echo '</tr>';
    }
?>

protected/views/teacher/goib/absents.php
    <script type="text/javascript">
        function sendAbsent(id){
            var upd="#getUpd_"+id;
        $('#abs_'+id).click(function(event ){
            event.preventDefault();
            var form_data = $(this).closest('form').serialize();
//            var formValidation={
//            'sId'              : this.form.shedId.value,
//            'uId'              : this.form.userId.value,
//            'tId'              : this.form.type.value,
//            'check'            : services
//            };
            $.ajax({
                type: "POST",
                url: "<?php echo Yii::app()->createUrl("teacher/teach"); ?>",
                data: form_data,
                cache: false,
                error: function(){
                },
                beforeSend: function(){
                    $('#abs_'+id).attr('disabled', 'disabled');
                },
                success: function(data){
                     $('#getUpd_'+id).html(data);
                }
            });
        });   
    };

    </script>
<?php
$this->pageTitle=Yii::app()->name .' - Гузоштани ғоиб';

$this->breadcrumbs=array(
       'Ғоибҳо'=>array('teacher/darsho'),
        $shedual->subject->subject->subject
);

$groupClass=  Groupin::model()->with('user')->findAll(
        array('condition'=>'groupId='.$shedual->groupId, 'order'=>'fname ASC')
        );

$expStart=explode('-',$shedual->dateStart);
   $day=$expStart[2];
    if($expStart[1]<10){
        $str=  substr($expStart[1], 1,1);
        $month=$str;
    }else{
        $month=$expStart[1];
    }
   $year=$expStart[0];
   
// There dateRest Begin 
   
   $expRest=explode(',',$shedual->dateRest);
    $list=array();
    for($i=0;$i<=count($expRest);$i++){
        $list[$i]=isset($expRest[$i]) ? $expRest[$i] : '' ;
    }

    function getWeek($day, $month, $year){
    
    $week=date('N',mktime(0, 0, 0, $month, $day-1, $year));
    if($week==1){
        $wee="Душанбе";
    }elseif($week==2){
        $wee="Сешанбе";
    }elseif($week==3){
        $wee="Чоршанбе";
    }elseif($week==4){
        $wee="Панҷшанбе";
    }elseif($week==5){
        $wee="Ҷумъа";
    }elseif($week==6){
        $wee="Шанбе";
    }elseif($week==7){
        $wee="Якшанбе";
    }
    return $wee;
}
    
?>
<section class="content">

<div style="overflow-x: auto">
<table id="table_reload" class="table table-bordered table-striped table-hover dataTable" role="grid" width="2000">
<thead style="background-color: #ABAAAA;">
  <th>№:</th>
  <th>Ному насаб</th>
  
  
  <?php
 //echo $shedual->dateStart; 
  $r=1;
    if($shedual->subject->subject->credit==6){
        $ruzho=  Type::model()->findAll(array(
        'condition'=>'id Between 1 and 18'
    ));
    
    for($i = 1;$i<=16+count($expRest);$i++){
       $data=date("Y-m-d", mktime(0, 0, 0, $month, $day++, $year));
      $week=  getWeek($day, $month, $year);
      if(in_array($data,$list)){
            echo '';
        }else{
            if($r==8){
            echo '<td colspan=2 align="center">Рӯзи '.$r++.', C. Марҳилавӣ <br>'.$data.'<br>'.$week.'</td>';
            }elseif($r==16){
                echo '<td colspan=2 align="center">Рӯзи '.$r++.', C. Марҳилавӣ <br>'.$data.'<br>'.$week.'</td>';
            }else{
                echo '<td>Рӯзи '.$r++.',<br>'.$data.'<br>'.$week.'</td>';
            }
        } 
        }
    }elseif($shedual->subject->subject->credit==4){
        $ruzho=  Type::model()->findAll(array(
        'condition'=>'id NOT IN(1,2,10,11,19,20,21,22,23,24,25)'
    ));
    for($i = 1;$i<=12+count($expRest);$i++){
       $data=date("Y-m-d", mktime(0, 0, 0, $month, $day++, $year));
      $week=  getWeek($day, $month, $year);
      if(in_array($data,$list)){
            echo '';
        }else{
            if($r==6){
            echo '<td colspan=2 align="center">Рӯзи '.$r++.', C. Марҳилавӣ <br>'.$data.'<br>'.$week.'</td>';
            }elseif($r==12){
                echo '<td colspan=2 align="center">Рӯзи '.$r++.', C. Марҳилавӣ <br>'.$data.'<br>'.$week.'</td>';
            }else{
                echo '<td>Рӯзи '.$r++.',<br>'.$data.'<br>'.$week.'</td>';
            }
        } 
        }
    }elseif($shedual->subject->subject->credit==2){
        $ruzho=  Type::model()->findAll(array(
        'condition'=>'id Between 1 and 6'
    ));
    }
  
  ?>
</thead>
    <tbody>
       <?php
           //$this->renderDynamic('goib');
       echo $this->renderPartial('goib/_absent', array('groupClass'=>$groupClass,'ruzho'=>$ruzho,'shedual'=>$shedual));

       ?> 
    </tbody>
</table>
    
    </div>
    </section>

protected/views/teacher/goib/ruihat.php
<?php

$Teacher=Teachers::model()->findByAttributes( array('userId'=>Yii::app()->session['user']['id'], 'status'=>1));
if(isset($Teacher))
$Subject=Subject::model()->findAll( array('condition'=>'teacherId='.$Teacher->id.' and status=1'));
//$groupClass=  Group::model()->findAllByAttributes(
//        array('groupId'=>$groupin->groupId, 'status'=>1)
//        );

$this->pageTitle=Yii::app()->name .' - Руйхати гурӯҳ';

$this->breadcrumbs=array(
       'Руйхати гурӯҳ'
);
echo '<section class="content">';
echo '<table class="table table-hover table-bordered table-striped dataTable" width="100%">';
echo '<th>#</th>';
echo '<th>Фанн</th>';
echo '<th>Гурӯҳ</th>';
echo '<th>Сикл</th>';
echo '<th>Сем</th>';
echo '<th>Кредит</th>';
echo '<th>Ҳолат</th>';
$num=1;
if(isset($Teacher))
foreach ($Subject as $subject){
    $shedual=Users::getAllShedual($subject->idSubject);
    
    foreach ($shedual as $shed){
       echo '<tr>';
       echo '<td>'.$num++.'</td>';
        $group=Users::getGroups($shed->groupId);
        echo '<td>'.$subject->subject->subject.'</td>';
        echo '<td><a href="'.Yii::app()->createUrl('teacher/goib',array('id'=>$shed->idShedual)).'">'.$group->course.'_'.$group->ihtisos->code.' '.$group->class.'</a></td>';
        echo '<td>'.$shed->cikl.'</td>';
        echo '<td>'.$shed->semestr.'</td>';
        echo '<td>'.$subject->subject->credit.'</td>';
        if($shed->status==1){
            echo '<td><span class="label label-success"><i class="fa fa-check-square"></i></span></td>';
        }

      echo '</tr>';

    }

}
echo '</table>';

echo '</section>';
?>