protected/controllers/KaidController.php
<?php

class KaidController extends Controller {
    public $layout='//layouts/admin';

    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('dovtalab','listgroup','ruihat',
                    'group','upddovtalab','updgroup','Addgroup',
                    'ihtisos','icreate','updateIhtisos','nozir'),
                'roles'=>array('4'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }
    
    public function actionDovtalab(){

        if (Yii::app()->user->isGuest)
            $this->redirect(Yii::app()->createUrl('login/index'));

        $model=new User;
        if(isset($_POST['User'])){
            $num=rand(10000,99999);
            $login='st'.$num;
            $password=md5($login);
                $model->attributes=$_POST['User'];
            $model->login=$login;
            $model->password=$password;
            $model->avatar="/dist/img/user6-128x128.jpg";
            $model->datecreate=new CDbExpression('NOW()');
            $model->lastupdate=new CDbExpression('NOW()');
            $model->accessId=1;
            $model->status=1;
            if($model->validate()){

                if($model->save())
                    Yii::app()->user->setFlash('success', 'Довталаб бо муваффақият дохил карда шуд!');
                    $this->refresh();
                }

        }


        $this->render('dovtalab',array('model'=>$model));
        
    }

    public function actionRuihat(){

        if (Yii::app()->user->isGuest)
            $this->redirect(Yii::app()->createUrl('login/index'));

        $model=new User;
        $this->render('ruihat',array('model'=>$model));
        
    }

    public function actionGroup($id=null){

        if (Yii::app()->user->isGuest)
            $this->redirect(Yii::app()->createUrl('login/index'));
        if(!is_null($id)) $model=$this->loadGroup($id);

        $model=new Group;
        if(isset($_POST['Group'])){
            $model->attributes=$_POST['Group'];
            $model->datecreate=new CDbExpression('NOW()');
            $model->lastupdate=new CDbExpression('NOW()');
            $model->status=1;
            if($model->validate() && $model->save()){
                Yii::app()->user->setFlash('success', 'Гурӯҳ бо муваффақият дохил карда шуд!');
                $this->refresh();
            }
        }
        $this->render('group',array('model'=>$model));
        
    }

    public function actionListgroup(){

        if (Yii::app()->user->isGuest)
            $this->redirect(Yii::app()->createUrl('login/index'));

        $this->render('listgroup');
        
    }

    public function actionUpddovtalab($id){
    $model=$this->loadUser($id);

        if(isset($_POST['User'])){
            $model->attributes=$_POST['User'];
            if($model->validate()){

                if($model->update()){
                    Yii::app()->user->setFlash('success', 'Довталаб бо муваффақият азнав карда шуд!');
                    $this->redirect(array('kaid/dovtalab'));
                }

            }


        }else{
            $this->render('dovtalab',array('model'=>$model));
        }

    }

    public function actionUpdgroup($id){

        $model=$this->loadGroup($id);

        if(isset($_POST['Group'])){
            $model->attributes=$_POST['Group'];
            $model->lastupdate=new CDbExpression('NOW()');

            if($model->validate() && $model->update()){
                Yii::app()->user->setFlash('success', 'Гурӯҳ бо муваффақият азнав карда шуд!');
                $this->redirect(array('kaid/group'));
            }
        }else{
            $this->render('group',array('model'=>$model));
        }

    }

    public function actionAddgroup(){
        if(isset($_POST['uId']) || isset($_POST['gId'])){
           $uId=intval($_POST['uId']);
           $gId=intval($_POST['gId']);
            $gropuin= new Groupin;
            $gropuin->groupId=$gId;
            $gropuin->userId=$uId;
            $gropuin->datecreate=new CDbExpression('NOW()');
            $gropuin->status=1;
            if($gropuin->save())
                echo 1;
        }
    }

    public function actionIhtisos(){

        $model=Ihtisos::model()->findAll();

        $this->render('ihtisos',array('model'=>$model));
    }

    public function actionIcreate()
    {
        $model=new Ihtisos;

        // Uncomment the following line if AJAX validation is needed
       // $this->performAjaxValidation($model,'test-form');

        if(isset($_POST['Ihtisos']))
        {
            $model->attributes=$_POST['Ihtisos'];
            $model->datecreate=new CDbExpression('NOW()');
            $model->status=1;
            if($model->validate()){

                if($model->save())
                    Yii::app()->user->setFlash('success', 'Довталаб бо муваффақият дохил карда шуд!');
                $this->redirect(array('kaid/ihtisos'));
            }
        }

        $this->render('ihtisos/create',array(
            'model'=>$model,
        ));
    }

    public function actionUpdateIhtisos($id)
    {
        $model=$this->loadModel($id);


        //$this->performAjaxValidation($model,'test-form');

        if(isset($_POST['Ihtisos']))
        {
            $model->attributes=$_POST['Ihtisos'];
            if($model->validate() && $model->save())
                $this->redirect(array('kaid/ihtisos'));
        }

        $this->render('ihtisos/update',array(
            'model'=>$model,
        ));
    }

    public function loadUser($id)
    {
        $model=User::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    public function loadGroup($id)
    {
        $model=Group::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    protected function performAjaxValidation($model,$form)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']===$form)
        {
            echo CActiveForm::validate($model);
        }
    }
    public function loadModel($id)
    {
        $model=Ihtisos::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }
}

?>

protected/views/kaid/dovtalab.php
<?php
$this->pageTitle=Yii::app()->name .' - Қайди довталабон';

$this->breadcrumbs=array(
    'Қайди довталабон'
);
?>
<script>
      $(function () {
        $("#myTable").DataTable();
      });
</script>
<section class="content">
    <div class="row">

        <div class="col-md-6">
            <?php if (Yii::app()->user->hasFlash('success')): ?>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?php echo Yii::app()->user->getFlash('success'); ?>
                </div>
            <?php endif; ?>
             <div class="box box-info" style="position: relative;">
                <div class="box-header ui-sortable-handle" style="cursor: pointer;">
                  <i class="fa fa-user-plus text-yellow"></i>
                  <h3 class="box-title">Қайди довталабон</h3>

                </div>
                 <div class="box-body">
                <?php echo $this->renderPartial('includes/_dovt', array('model'=>$model)); ?>
              </div>
              </div>
        </div>
        <section id="_upd" class="col-lg-6 connectedSortable ui-sortable">
            <div class="box box-success"  style="position: relative;">
                <div class="box-header ui-sortable-handle" style="cursor: pointer;">
                  <i class="fa fa-users text-blue"></i>
                  <h3 class="box-title">Қайди довталабон</h3>
                </div>
                <div class="box-body">
                                    <table id="myTable" class="table table-bordered table-hover dataTable" width="100%" role="grid">
                                              <thead>
                                                  <tr role="row">
                                                        <th>#</th>
                                                        <th>Н. Н. Д.</th>

                                                        <th>Амалиёт</th>
                                                   </tr>
                                              </thead>
                                              <tbody>
                                                  <?php
                                                  $i=1;
                                                  $users = User::model()->findAll(array('condition' =>'accessId=1 and status=1'));

                                                  foreach ($users as $user) {
                                                      //$check = Users::checkUserInGroupin($user->id);
                                                      //if (empty($check)) {
                                                      echo '<tr>';
                                                      echo '<td>'.$i++.'</td>';
                                                         echo '<td>'.$user->fname.' '.$user->name.' '.$user->lname.'</td>';
                                                         echo '<td><a href="'.Yii::app()->createUrl("kaid/upddovtalab/".$user->id).'" class="btn btn-xs btn-success"><i class="fa fa-edit"></i> Азнавкардан</a></td>';
                                                      echo '</tr>';     
                                                      //} 



                                                      //echo '<br>';
                                                  }
                                                  ?> 
                                              <tfoot>
                                                  <tr role="row">
                                                        <th>#</th>
                                                        <th>Н. Н. Д.</th>
                                                        <th>Амалиёт</th>
                                                   </tr>
                                              </tfoot>
                                    </table>
                    </div>
                </div>



        </section>
    </div>


</section>

protected/views/kaid/group.php
<?php
$this->pageTitle=Yii::app()->name .' - Ташкили гурӯҳ';

$this->breadcrumbs=array(
    'Ташкили гурӯҳ'
);
?>
<script>
      $(function () {
        $("#myTable").DataTable();
      });
</script>

<section class="content">
    <div class="row">

 <section class="col-lg-7 connectedSortable ui-sortable">
     <?php if (Yii::app()->user->hasFlash('success')): ?>
         <div class="alert alert-success alert-dismissable">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
             <?php echo Yii::app()->user->getFlash('success'); ?>
         </div>
     <?php endif; ?>
            <div class="box box-info" style="position: relative;">
                 <div class="box-header ui-sortable-handle" style="cursor: pointer;">
                     <i class="fa fa-envelope"></i>
                  <h3 class="box-title">Қайди гурӯҳ</h3>
                 
                </div>
                 <div class="box-body">
                <?php echo $this->renderPartial('includes/_group', array('model'=>$model)); ?>
              </div>
              </div>
        </section>
        <section class="col-lg-5 connectedSortable ui-sortable">
            <div class="box box-success" style="position: relative;">
                <div class="box-header ui-sortable-handle" style="cursor: pointer;">
                  <i class="fa fa-envelope"></i>
                  <h3 class="box-title">Руйхати гурӯҳ</h3>
                </div>
                <div class="box-body">
                    </div>
                <table id="myTable" class="table table-bordered table-hover dataTable" width="100%" role="grid">
                    <thead>
                    <tr role="row">
                        <th>#</th>
                        <th>Н. Н. Д.</th>

                        <th>Амалиёт</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i=1;
                    $groups = Group::model()->findAll(array('condition' =>'status=1'));

                    foreach ($groups as $group) {
                        //$check = Users::checkUserInGroupin($user->id);
                        //if (empty($check)) {
                        echo '<tr>';
                        echo '<td>'.$i++.'</td>';
                        echo '<td>'.$group->course.'_'.$group->ihtisos->code.$group->class.'</td>';
                        echo '<td><a href="'.Yii::app()->createUrl('kaid/updgroup/'.$group->idGroup).'" class="btn btn-xs btn-success"><i class="fa fa-edit"></i> Азнавкардан</a></td>';
                        echo '</tr>';
                        //}



                        //echo '<br>';
                    }
                    ?>
                    <tfoot>
                    <tr role="row">
                        <th>#</th>
                        <th>Н. Н. Д.</th>
                        <th>Амалиёт</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </section>

    </div>
   
</section>

protected/views/kaid/ihtisos.php
<?php
$this->pageTitle=Yii::app()->name .' - Ихтисос';

$this->breadcrumbs=array(
    'Ихтисос'
);
?>

<section class="content">
    <a class="btn btn-app" href="<?php echo Yii::app()->createUrl("kaid/icreate") ?>">
        <i class="fa fa-edit"></i> Ворид кардан
    </a>
    <table class="table table-bordered table-hover table stripped">
    <thead>
    <tr>
        <th>#</th>
        <th>Ихтисос</th>
        <th>Коди ихтисос</th>
        <th>Ҳолат</th>
        <th>Азнавкардан</th>
    </tr>
    </thead>

        <tbody>


    <?php
$i=1;
 foreach($model as $ihtisos){
     echo '<tr>';
     echo '<td>'.$i++.'</td>';
     echo '<td>'.$ihtisos->ihtisos.'</td>';
     echo '<td>'.$ihtisos->code.'</td>';
     if ($ihtisos->status == 1)
         echo '<td id="btn_' . $ihtisos->id. '"><button onclick="update(' . $ihtisos->id . ')" class="btn btn-success">ON</button></td>';
     else
         echo '<td id="btn_' . $ihtisos->id . '"><button onclick="update(' . $ihtisos->id . ')" class="btn btn-danger">OFF</button></td>';
     echo '<td><a class="btn btn-primary" href="'.Yii::app()->createUrl("kaid/updateihtisos/".$ihtisos->id).'"><i class="fa fa-pencil text-red"></i> Азнавкардан</td>';
 }
    echo '</tr>';
    ?>
        </tbody>
        <tfoot>
        <th>#</th>
        <th>Ихтисос</th>
        <th>Коди ихтисос</th>
        <th>Ҳолат</th>
        <th>Азнавкардан</th>
        </tfoot>
    </table>
</section>

protected/views/kaid/listgroup.php
<?php
$this->pageTitle=Yii::app()->name .' - Руйхати гурӯҳ';

$this->breadcrumbs=array(
    'Руйхати гурӯҳ'
);
?>
<section class="content">
    <div class="col-md-6" style="float: none;">
              <div class="box box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">Руйхати гурӯҳ</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <div class="box-group" id="accordion">
                      <?php
               $i=1;
               $groups = Group::model()->findAll(array('condition' =>'status=1'));

               foreach ($groups as $group) {
                            echo '<div class="panel box box-danger">';
                            
                            echo ' <div class="box-header with-border">';
                            echo '<h4 class="box-title">';
                            echo '<a data-toggle="collapse" data-parent="#accordion" href="#collapse'.$group->idGroup.'">
                            '.$group->course.'_'.$group->ihtisos->code.$group->class.' ('.Users::countGroupins($group->idGroup).')</a>';
                            echo '</h4>';
                            echo ' </div>';
                            
                            
                            echo '<div id="collapse'.$group->idGroup.'" class="panel-collapse collapse">';
                            echo '<div class="box-body">';
                            echo '<table class="table table-hover table-bordered">';
                            echo '<thead>';
                            echo '<th>#</th>';
                            echo '<th>Н.Ф.Д</th>';
                            echo '<th>Логин</th>';
                           // echo '<th>Хориҷ</th>';
                            echo '</thead>';
                            $groupins=Users::Groupins($group->idGroup);
                            $i=1;
                            foreach( $groupins as $groups){
                            echo '<tr>';
                            echo '<td>'.$i++.'</td>';
                                echo '<td>'.$groups->user->fname.' '.$groups->user->name.' '.$groups->user->lname."</td>";
                                echo '<td>'.$groups->user->login."</td>";
                                //echo '<td><a href="javascript::void()" class="btn btn-danger btn-xs">Хориҷ</a></td>';
                            echo '</tr>';
                         }
                            echo '</table>';
                            echo '</div>';
                            echo '</div>';
                            echo '</div>';       
                          }
                                                  ?> 
                    <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                    
                        
                     
                        
                          
                        
                     
                        
                        
                     
                        
                          
                        </div>
                     
                        
                        
                    
                    
                  </div>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            
</section>

protected/views/kaid/ruihat.php
<?php
$this->pageTitle=Yii::app()->name .' - Руйхати довталабон';

$this->breadcrumbs=array(
    'Руйхати довталабон'
);

$models=Group::model()->findAll(array('condition'=>'status=1'));
$data=array();
foreach($models as $m)
    $data[$m->idGroup]=$m->course.'_'.$m->ihtisos->code.$m->class;
?>
<script>
      $(function () {
        $("#myTable").DataTable();
      });
    function changeDrop(id){
        $('#but_'+id).removeAttr('disabled');
        $('#but_'+id).removeClass('btn-primary');
        $('#but_'+id).addClass('btn-success');
    }
    function sendGroup(id){
        data=$('#form_'+id).serialize();
        $.ajax({
            type: 'POST',
            url: "<?php echo $this->createUrl("kaid/addgroup");?>",
            data: data,
            cache: false,
            error: function() {
               alert('nawud');
            },
            beforeSend: function() {
                $('input[button]').attr('disabled');
            },
            success: function(data) {
                if(data=1){
                    $('input[button]').attr('disabled');
                $('tr#obn_'+id).fadeOut();
                //history.go(0);
                }
            }
        });
    }
</script>
<section id="con" class="content table-responsive">
     <table id="myTable" class="table table-bordered table-hover dataTable" width="100%" role="grid">
                                              <thead>
                                                  <tr role="row">
                                                        <th>#</th>
                                                        <th>Н. Н. Д.</th>
                                                        <th>Соли таваллуд</th>
                                                        <th>Ҷинс</th>
                                                        <th>Телефон</th>
                                                        <th>Суроға</th>
                                                        <th>Амалиёт</th>
                                                   </tr>
                                              </thead>
                                              <tbody>
                                                  <?php
                                                  $i=1;
                                                  $users = User::model()->findAll(array('condition' =>'accessId=1'));

                                                  foreach ($users as $user) {
                                                      $check = Users::checkUserInGroupin($user->id);
                                                      if (empty($check)) {
                                                      echo '<tr id="obn_'.$user->id.'" disabled="disabled">';
                                                      echo '<td>'.$i++.'</td>';
                                                         echo '<td>'.$user->fname.' '.$user->name.' '.$user->lname.'</td>';
                                                         echo '<td>'.$user->birthday.'</td>';
                                                         
                                                         if($user->gender==1){
                                                             echo '<td> Зан </td>';
                                                         }else{
                                                             echo '<td> Мард </td>';
                                                         }
                                                          echo '<td>'.$user->number_phone.'</td>';
                                                          echo '<td>'.$user->address.'</td>';
                                                          echo '<td><form method="post" id="form_'.$user->id.'" onsubmit="return false;"><input type="hidden" value="'.$user->id.'" name="uId">'.CHtml::dropDownList('gId','text',$data,array('id'=>'drop_'.$user->id,'onClick'=>'changeDrop('.$user->id.')')).' &nbsp; <button class="btn btn-primary btn-xs" id="but_'.$user->id.'" onclick="sendGroup('.$user->id.')" disabled="disabled"><i class="fa fa-group"></i>&nbsp;Дохил кардан</button></form></td>';
                                                      echo '</tr>';     
                                                      } 
                                                        


                                                      //echo '<br>';
                                                  }
                                                  ?> 
                                              <tfoot>
                                                  <tr role="row">
                                                        <th>#</th>
                                                        <th>Н. Н. Д.</th>
                                                        <th>Соли таваллуд</th>
                                                        <th>Ҷинс</th>
                                                        <th>Телефон</th>
                                                        <th>Суроға</th>
                                                        <th>Амалиёт</th>
                                                   </tr>
                                              </tfoot>
                                          </table>
    
</section>